DROP TABLE IF EXISTS public.example_child CASCADE;
DROP TABLE IF EXISTS public.example CASCADE;

CREATE TABLE IF NOT EXISTS public.example
(
  id_parent BIGSERIAL NOT NULL,
  status CHAR(3) NOT NULL,
  enabled BOOLEAN DEFAULT false,
  created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT PK_EXAMPLE PRIMARY KEY (id_parent)
);

COMMENT ON TABLE public.example IS 'Example table comment';
COMMENT ON COLUMN public.example.id_parent IS 'Autogenerated id';

CREATE TABLE IF NOT EXISTS public.example_child
(
  id_child BIGSERIAL NOT NULL,
  id_parent BIGINT NOT NULL,
  CONSTRAINT PK_EXAMPLE_CHILD PRIMARY KEY (id_child),
  CONSTRAINT FK_EXAMPLE_PARENT FOREIGN KEY (id_parent) REFERENCES public.example(id_parent)
)
